import { notFound } from "next/navigation";
import Link from "next/link";
import { getProjectResults, listProjects, hasRichDashboard } from "@/lib/projects/storage";
import MdContent from "./md-content";
import "./dashboard.css";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// Order modules in a logical reading flow when present.
const MODULE_ORDER = [
  "_meta",
  "worldbuilding",
  "characters",
  "locations",
  "teaser_pool",
  "fragments",
  "endings",
  "refs",
  "storyboard_analysis",
];

function sortModules<T extends { module: string }>(modules: T[]): T[] {
  return modules.slice().sort((a, b) => {
    const ai = MODULE_ORDER.indexOf(a.module);
    const bi = MODULE_ORDER.indexOf(b.module);
    if (ai === -1 && bi === -1) return a.module.localeCompare(b.module);
    if (ai === -1) return 1;
    if (bi === -1) return -1;
    return ai - bi;
  });
}

function labelFor(module: string): string {
  if (module === "_meta") return "Pitch";
  return module.replace(/_/g, " ");
}

export default async function ProjectPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  const projects = await listProjects();
  const project = projects.find((p) => p.projectId === slug);
  if (!project) return notFound();

  // If a rich dashboard.html exists (produced by meta-creation / Claude Code),
  // serve it full-screen in an iframe — same identity as the NBS dashboard.
  if (await hasRichDashboard(slug)) {
    return (
      <iframe
        src={`/api/dashboard/${slug}`}
        title={String(project.meta?.originalFilename ?? slug)}
        style={{
          position: "fixed",
          inset: 0,
          width: "100%",
          height: "100dvh",
          border: "none",
        }}
      />
    );
  }

  const results = sortModules(await getProjectResults(slug));
  const title = String(project.meta?.originalFilename ?? slug);
  const uploadedAt = project.meta?.uploadedAt
    ? String(project.meta.uploadedAt).slice(0, 16).replace("T", " ")
    : null;

  return (
    <div className="tsw-dashboard">
      <div className="tsw-wrapper">
        <nav className="tsw-nav" aria-label="Dashboard sections">
          <div className="tsw-nav-brand">
            <strong>The soft War</strong>
            <br />
            project {slug}
          </div>

          <ul className="tsw-nav-links">
            <li>
              <Link href="/projects">← all projects</Link>
            </li>
          </ul>

          {results.length > 0 && (
            <ul className="tsw-nav-links">
              {results.map((r) => (
                <li key={r.module}>
                  <a href={`#${r.module}`}>{labelFor(r.module)}</a>
                </li>
              ))}
            </ul>
          )}
        </nav>

        <main className="tsw-main">
          <header className="tsw-hero">
            <h1>{title}</h1>
            <p className="lead">
              Development bible generated by <em>The soft War</em>.
            </p>
            <div className="tsw-meta-row">
              {uploadedAt && (
                <span>
                  <strong>uploaded</strong> · {uploadedAt}
                </span>
              )}
              <span>
                <strong>project id</strong> · {slug}
              </span>
              <span>
                <strong>modules</strong> · {results.length}
              </span>
            </div>
          </header>

          {results.length === 0 ? (
            <section className="tsw-section">
              <div className="tsw-section-label">Status</div>
              <h2>Not analyzed yet.</h2>
              <p>
                The script is queued in the backlog. Run Claude Code on the
                BACKLOG.md to generate the modules.
              </p>
            </section>
          ) : (
            results.map((r) => (
              <section key={r.module} id={r.module} className="tsw-section">
                <div className="tsw-section-label">{labelFor(r.module)}</div>
                <MdContent>{r.markdown}</MdContent>
              </section>
            ))
          )}
        </main>
      </div>
    </div>
  );
}
